name: CI/CD

on: 
  push: 
    branches: 
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Navigate to project directory
        run: cd src

      - name: Restore dependencies
        run: |
          cd src
          dotnet restore Manage-CLB-HTSV.generated.sln

      - name: Build project
        run: |
          cd src
          dotnet build Manage-CLB-HTSV.generated.sln --configuration Release

      - name: Test project
        run: |
          cd src
          dotnet test Manage-CLB-HTSV.generated.sln

      - name: Build Docker image
        run: |
          cd src
          docker build --build-arg DB_PASSWORD2=${{ secrets.DB_PASSWORD2 }} \
                       --build-arg SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
                       --build-arg PFX_PASSWORD=${{ secrets.PFX_PASSWORD }} \
                       --build-arg MICROSOFT_CLIENT_ID=${{ secrets.MICROSOFT_CLIENT_ID }} \
                       --build-arg MICROSOFT_CLIENT_SECRET=${{ secrets.MICROSOFT_CLIENT_SECRET }} \
                       -t phuchoang1910/webapp_htsv:latest .

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                   

      - name: Push Docker image
        run: |
          docker push phuchoang1910/webapp_htsv:latest

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            docker pull phuchoang1910/webapp_htsv:latest
            docker stop webapp_htsv || true && docker rm webapp_htsv || true
            docker run -d --name webapp_htsv -p 80:80 -p 443:443 phuchoang1910/webapp_htsv:latest
