version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_PASSWORD2=${DB_PASSWORD2:-defaultpassword}
        - SMTP_PASSWORD=${SMTP_PASSWORD:-defaultsmtp}
        - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID:-}
        - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET:-}
    container_name: webapp_htsv_dev
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./logs:/app/logs
      - ./wwwroot/userimages:/app/wwwroot/userimages
      - ./wwwroot/newsimages:/app/wwwroot/newsimages
      - ./wwwroot/qrcode:/app/wwwroot/qrcode
      - ./wwwroot/minhchunghd:/app/wwwroot/minhchunghd
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - htsv-network

networks:
  htsv-network:
    driver: bridge 